### ISSUE TITLE
Is there any developer tools for Toshiba Tmp96c141bfg IC? 

### ISSUE THREAD

**Issue by mohammad0663** [MDK-Packs/Pack#2]
Is there any developer tools for Toshiba Tmp96c141bfg IC? I need to program this IC with Keil and will appreciate any help or guidance.

**Comment by jkrech** [comment]
You are not looking in the right place.
Keil MDK product is targeted at Arm Cortex-M processor based devices. As far as I can see from a brief web search, the Tmp96c141bfg devices is a 16-bit Toshiba proprietary Microcontroller. You should contact Toshiba directly for tools support.
Note, the classic Keil tools only support C51, C166 and C251 based devices (www.keil.com/dd)

Regards,
Joachim
